/**  CHARACTERS */
export const INIT_CHARACTERS = "INIT_CHARACTERS";

export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAIL = "FETCH_CHARACTERS_FAIL";

export const FILTER_CHARACTERS_START = "FILTER_CHARACTERS_START";
export const FILTER_CHARACTERS_SUCCESS = "FILTER_CHARACTERS_SUCCESS";
export const FILTER_CHARACTERS_FAIL = "FILTER_CHARACTERS_FAIL";

export const IDS_CHARACTERS_START = "IDS_CHARACTERS_START";
export const IDS_CHARACTERS_SUCCESS = "IDS_CHARACTERS_SUCCESS";
export const IDS_CHARACTERS_FAIL = "IDS_CHARACTERS_FAIL";

/**  LOCATIONS */
export const FETCH_LOCATIONS_START = "FETCH_LOCATIONS_START";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAIL = "FETCH_LOCATIONS_FAIL";

export const FILTER_LOCATIONS_START = "FILTER_LOCATIONS_START";
export const FILTER_LOCATIONS_SUCCESS = "FILTER_LOCATIONS_SUCCESS";
export const FILTER_LOCATIONS_FAIL = "FILTER_LOCATIONS_FAIL";

export const IDS_LOCATIONS_START = "IDS_LOCATIONS_START";
export const IDS_LOCATIONS_SUCCESS = "IDS_LOCATIONS_SUCCESS";
export const IDS_LOCATIONS_FAIL = "IDS_LOCATIONS_FAIL";

/**  EPISODES */
export const FETCH_EPISODES_START = "FETCH_EPISODES_START";
export const FETCH_EPISODES_SUCCESS = "FETCH_EPISODES_SUCCESS";
export const FETCH_EPISODES_FAIL = "FETCH_EPISODES_FAIL";

export const FILTER_EPISODES_START = "FILTER_EPISODES_START";
export const FILTER_EPISODES_SUCCESS = "FILTER_EPISODES_SUCCESS";
export const FILTER_EPISODES_FAIL = "FILTER_EPISODES_FAIL";

export const IDS_EPISODES_START = "IDS_EPISODES_START";
export const IDS_EPISODES_SUCCESS = "IDS_EPISODES_SUCCESS";
export const IDS_EPISODES_FAIL = "IDS_EPISODES_FAIL";

/**  FOR ALL */
export const FIRST_PAGE = "FIRST_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
